Repository NationalBankBelgium/code-style, pull requests merged in 2020-02, with the labels that each got.

#21 Bugfix/readme minor errors
  CONTRIBUTING.md
  lib/prettier/README.md
Labels: documentation

#25 chore(all): update dependencies + adapt release-it and lint-staged configs
  .release-it.json
  commitlint.config.js
  package-lock.json
  package.json
Labels: bug, dependencies

#26 Feature/add config validation tests
  .travis.yml
  lib/stylelint/9.10.x/stylelint.config.js
  package.json
  test.sh
Labels: bug, enhancement

#28 codelyzer - update codelyzer configs
  lib/codelyzer/4.5.x/tslint.json
  lib/codelyzer/5.0.x/README.md
  lib/codelyzer/5.0.x/package.json
  lib/codelyzer/5.0.x/tslint.json
  lib/codelyzer/5.1.x/README.md
  lib/codelyzer/5.1.x/package.json
  lib/codelyzer/5.1.x/tslint.json
  lib/codelyzer/5.2.x/README.md
  lib/codelyzer/5.2.x/package.json
  lib/codelyzer/5.2.x/tslint.json
  lib/codelyzer/README.md
  package-lock.json
  package.json
Labels: codelyzer, enhancement

#33 fix(stylelint): disable 3 stylelint rules incorrectly enabled starting from stylelint 10.0.x
  lib/stylelint/10.0.x/stylelint.config.js
  lib/stylelint/10.1.x/stylelint.config.js
  lib/stylelint/11.0.x/stylelint.config.js
  lib/stylelint/11.1.x/stylelint.config.js
  lib/stylelint/12.0.x/stylelint.config.js
  lib/stylelint/13.0.x/stylelint.config.js
Labels: bug, stylelint

#30 ci(build): replace travis by GitHub Actions
  .cz-config.js
  .editorconfig
  .github/workflows/build.yml
  .travis.yml
  README.md
  RELEASE.md
  build.sh
  release-publish.sh
  scripts/ci/_ghactions-group.sh
  scripts/ci/_travis-fold.sh
  scripts/ci/print-logs.sh
  test.sh
Labels: ci, enhancement
